version: 2
updates:
  - package-ecosystem: pip
    directory: /diff-generator/
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directories:
      - /assets
      - /bouncer
      - /datagovuk
      - /logs
      - /mobile-backend
      - /service-domain-redirect
      - /tld-redirect
      - /www
    schedule:
      interval: daily
