name: Build and push diff generator image
on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: 'Commit, tag or branch name to deploy'
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - "diff-generator/*"
jobs:
  build-and-publish-image:
    name: Build and publish image
    uses: alphagov/govuk-infrastructure/.github/workflows/build-and-push-multiarch-image.yml@main
    with:
      gitRef: ${{ inputs.gitRef || github.ref }}
      dockerfilePath: diff-generator/Dockerfile 
      context: diff-generator
      ecrRepositoryName: govuk-fastly-diff-generator
    permissions:
      id-token: write
      contents: read
      packages: write
